default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: test123
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>

development:
  <<: *default
  database: patient_info_sys_development

dev:
  <<: *default
  database: patient_info_sys_dev

staging:
  <<: *default
  database: patient_info_sys_staging

production:
  <<: *default
  database: patient_info_sys_production

test:
  <<: *default
  database: patient_info_sys_test
